server: 
  port: 9001
spring: 
  application: 
    name: tensquare-base
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://101.132.168.237:3306/tensquare_base?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: root
  jpa:
    database: MySQL
    show‐sql: true
    generate‐ddl: true